import { KeyPerformanceMetricValue } from "./keyPerformanceMetrics"

export interface NebOption {
    label: string,
    htmlLabel: string,
    optionValue: NebOptionValue,
    // riskReduction: boolean,
    // valuePropositionIncrease: boolean,
    // decreaseCosts: boolean,
    isQualitative: boolean,
    howToCalculate: string,
    KPM: Array<KeyPerformanceMetricValue>,
    selected?: boolean
};

export type NebOptionValue = 'improvedImageOrReputation' |
    'improvedStakeholderRelationship' |
    'newCustomers' |
    'increasedCustomerSatisfaction' |
    'reduceCustomerLossThroughBetterPerformance' |
    'increasedCustomerLoyalty' |
    'improvedSupplyChainRelationships' |
    'increasedProductivity' |
    'lessTimeToMakeGoods' |
    'equipmentRunningWithoutNonconformingProduct' |
    'reduceMalfunctionOrBreakdownIndustrialTrucks' |
    'delayReplacementEquipment' |
    'fasterTimeMoreFlexibilityMoreProducts' |
    'improvedProductQualityMachineSource' |
    'improvedProductQualityOperatorSource' |
    'improvedProductQualityDebrisContamination' |
    'reduceProductionLossLaborMaterial' |
    'reducedRawMaterialLoss' |
    'reducedConsumables' |
    'additionalSpaceFromLayoutChanges' |
    'reducedLaborServiceAgreementAndOtherExpenses' |
    'reducedWearAndTear' |
    'reducedLaborCostsForProblemSolvingAndRepair' |
    'reduceHazardousWaste' |
    'reduceNonhazardousWaste' |
    'reduceProductWaste' |
    'reduceWaterConsumption' |
    'reduceSewageVolume' |
    'reduceDustEmissions' |
    'reduceChemicalEmissions' |
    'reduceRefrigerantGasEmissions' |
    'reduceOccupationalDangers' |
    'reducedNoiseExposure' |
    'improveAmbientAirQuality' |
    'improvedThermalComfort' |
    'improvedVisualComfort' |
    'improvedWorkingEnvironment' |
    'changeAddQualityJobs' |
    'justice40Initiatives' |
    'improvedStaffSatisfactionLoyalty' |
    'reduceStaffTurnover'


export const NebOptions: Array<NebOption> = [
    {
        label: "Improved image or reputation",
        htmlLabel: "Improved image or reputation",
        optionValue: "improvedImageOrReputation",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "salesGrowth", "customerSatisfactionRatings", "lostCustomerSales", "customerChurnRate", "supplierSatisfactionRatings"],
    },
    {
        label: "Improved stakeholder relationship",
        htmlLabel: "Improved stakeholder relationship",
        optionValue: "improvedStakeholderRelationship",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "salesGrowth", "customerSatisfactionRatings", "lostCustomerSales", "customerChurnRate", "supplierSatisfactionRatings"],
    },
    {
        label: "New customers",
        htmlLabel: "New customers",
        optionValue: "newCustomers",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "salesGrowth", "lostCustomerSales", "customerChurnRate"],
    },
    {
        label: "Increased customer satisfaction",
        htmlLabel: "Increased customer satisfaction",
        optionValue: "increasedCustomerSatisfaction",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "salesGrowth", "customerSatisfactionRatings", "lostCustomerSales", "customerChurnRate"],
    },
    {
        label: "Reduce customer loss through better performance: quality, cost and delivery",
        htmlLabel: "Reduce customer loss through better performance: quality, cost and delivery",
        optionValue: "reduceCustomerLossThroughBetterPerformance",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "salesGrowth", "customerSatisfactionRatings", "lostCustomerSales", "customerChurnRate"],
    },
    {
        label: "Increased customer loyalty",
        htmlLabel: "Increased customer loyalty",
        optionValue: "increasedCustomerLoyalty",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "salesGrowth", "customerSatisfactionRatings", "lostCustomerSales", "customerChurnRate"],
    },
    {
        label: "Improved supply chain relationships",
        htmlLabel: "Improved supply chain relationships",
        optionValue: "improvedSupplyChainRelationships",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "supplierSatisfactionRatings"],
    },
    {
        label: "Increased Productivity",
        htmlLabel: "Increased Productivity",
        optionValue: "increasedProductivity",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "salesGrowth", "productivityRateThroughput", "productionCosts", "cycleTimeToMakeGoods", "percentOnTimeToDueDate", "revenuePerEmployee", "perUnitProductCost", "percentCapacityUtilization", "overallEquipmentEffectiveness", "timeToIntroduceNewProducts"],
    },
    {
        label: "Less time to make goods",
        htmlLabel: "Less time to make goods",
        optionValue: "lessTimeToMakeGoods",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "salesGrowth", "productivityRateThroughput", "productionCosts", "cycleTimeToMakeGoods", "percentOnTimeToDueDate", "revenuePerEmployee", "perUnitProductCost", "percentCapacityUtilization", "overallEquipmentEffectiveness", "timeToIntroduceNewProducts", "workInProcess"],
    },
    {
        label: "More productive time equipment is running without nonconforming product",
        htmlLabel: "More productive time equipment is running without nonconforming product",
        optionValue: "equipmentRunningWithoutNonconformingProduct",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["numberEquipmentCausedDefects", "equipmentDowntime", "percentCapacityUtilization", "overallEquipmentEffectiveness", "percentProductionYield", "percentShrinkage", "hazardousDisposalCosts", "nonHazardousDisposalCosts", "percentTotalOrCost", "employeeEngagementSatisfaction"],
    },
    {
        label: "Reduced malfunction or breakdown industrial trucks, improve service for production/warehouse/shipping",
        htmlLabel: "Reduced malfunction or breakdown industrial trucks, improve service for production/warehouse/shipping",
        optionValue: "reduceMalfunctionOrBreakdownIndustrialTrucks",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["equipmentDowntime", "percentCapacityUtilization", "overallEquipmentEffectiveness", "forkTruckBreakdownTime", "maintenanceCost", "employeeEngagementSatisfaction"],
    },
    {
        label: "Delay cost replacement equipment, longer equipment life",
        htmlLabel: "Delay cost replacement equipment, longer equipment life",
        optionValue: "delayReplacementEquipment",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "usefulEquipmentLifeExtended", "maintenanceCost"],
    },
    {
        label: "Faster time, more flexibility, more products",
        htmlLabel: "Faster time, more flexibility, more products",
        optionValue: "fasterTimeMoreFlexibilityMoreProducts",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "percentCapacityUtilization", "overallEquipmentEffectiveness", "usefulEquipmentLifeExtended"],
    },
    {
        label: "Improved product quality - machine source",
        htmlLabel: "Improved product quality - machine source",
        optionValue: "improvedProductQualityMachineSource",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["productivityRateThroughput", "productionCosts", "cycleTimeToMakeGoods", "percentOnTimeToDueDate", "revenuePerEmployee", "perUnitProductCost", "numberEquipmentCausedDefects", "equipmentDowntime", "percentCapacityUtilization", "overallEquipmentEffectiveness", "defectiveProductionDollar", "defectRatePPMorDPM", "qualityCustomerComplaints", "qualityCustomerReturns", "percentProductionYield", "percentShrinkage", "maintenanceCost", "engineeringSupport"],
    },
    {
        label: "Improved product quality - operator source",
        htmlLabel: "Improved product quality - operator source",
        optionValue: "improvedProductQualityOperatorSource",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["productivityRateThroughput", "productionCosts", "cycleTimeToMakeGoods", "percentOnTimeToDueDate", "revenuePerEmployee", "perUnitProductCost", "defectiveProductionDollar", "defectRatePPMorDPM", "qualityCustomerComplaints", "qualityCustomerReturns", "percentProductionYield", "percentShrinkage", "maintenanceCost", "engineeringSupport", "employeeEngagementSatisfaction"],
    },
    {
        label: "Improved product quality - debris contamination",
        htmlLabel: "Improved product quality - debris contamination",
        optionValue: "improvedProductQualityDebrisContamination",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["perUnitProductCost", "percentCapacityUtilization", "defectiveProductionDollar", "defectRatePPMorDPM", "qualityCustomerComplaints", "qualityCustomerReturns"],
    },
    {
        label: "Reduce production loss - labor and material",
        htmlLabel: "Reduce production loss - labor and material",
        optionValue: "reduceProductionLossLaborMaterial",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["productivityRateThroughput", "productionCosts", "percentOnTimeToDueDate", "revenuePerEmployee", "perUnitProductCost", "defectiveProductionDollar", "defectRatePPMorDPM", "percentProductionYield", "percentShrinkage"],
    },
    {
        label: "Reduced raw material loss",
        htmlLabel: "Reduced raw material loss",
        optionValue: "reducedRawMaterialLoss",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["productionCosts", "revenuePerEmployee", "perUnitProductCost", "defectiveProductionDollar", "defectRatePPMorDPM", "percentProductionYield", "percentShrinkage", "hazardousDisposalCosts", "nonHazardousDisposalCosts"],
    },
    {
        label: "Reduce consumables",
        htmlLabel: "Reduce consumables",
        optionValue: "reducedConsumables",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["perUnitProductCost", "dollarConsumables"],
    },
    {
        label: "Additional space from layout/process changes",
        htmlLabel: "Additional space from layout/process changes",
        optionValue: "additionalSpaceFromLayoutChanges",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["productivityRateThroughput", "percentOptimizedSpace", "employeeEngagementSatisfaction"],
    },
    {
        label: "Reduced wear and tear, reduced replacement and repair parts",
        htmlLabel: "Reduced wear and tear, reduced replacement and repair parts",
        optionValue: "reducedWearAndTear",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["productivityRateThroughput", "equipmentDowntime", "percentCapacityUtilization", "overallEquipmentEffectiveness", "forkTruckBreakdownTime", "usefulEquipmentLifeExtended", "maintenanceCost"],
    },
    {
        label: "Reduced labor costs for problem solving and repair",
        htmlLabel: "Reduced labor costs for problem solving and repair",
        optionValue: "reducedLaborCostsForProblemSolvingAndRepair",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["productivityRateThroughput", "maintenanceCost", "engineeringSupport"],
    },
    {
        label: "Reduce hazardous waste",
        htmlLabel: "Reduce hazardous waste",
        optionValue: "reduceHazardousWaste",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "defectiveProductionDollar", "percentProductionYield", "percentShrinkage", "hazardousDisposalCosts", "percentTotalOrCost"],
    },
    {
        label: "Reduce nonhazardous waste",
        htmlLabel: "Reduce nonhazardous waste",
        optionValue: "reduceNonhazardousWaste",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "defectiveProductionDollar", "percentProductionYield", "percentShrinkage", "nonHazardousDisposalCosts", "percentTotalOrCost"],
    },
    {
        label: "Reduce product waste",
        htmlLabel: "Reduce product waste",
        optionValue: "reduceProductWaste",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "defectiveProductionDollar", "defectRatePPMorDPM", "percentShrinkage", "percentTotalOrCost"],
    },
    {
        label: "Reduce water consumption",
        htmlLabel: "Reduce water consumption",
        optionValue: "reduceWaterConsumption",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "consumptionCostWater"],
    },
    {
        label: "Reduce sewage volume",
        htmlLabel: "Reduce sewage volume",
        optionValue: "reduceSewageVolume",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "consumptionCostSewage"],
    },
    {
        label: "Reduce dust emission",
        htmlLabel: "Reduce dust emissions",
        optionValue: "reduceDustEmissions",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "totalLbsDust"],
    },
    // {
    //     label: "Reduce CO, CO2, NOx, SOx emissions",
    //     htmlLabel: "Reduce CO, CO<sub>2</sub>, NO<sub>x</sub>, SO<sub>x</sub> emissions",
    //     optionValue: "reduceChemicalEmissions",
    //     // riskReduction: true,
    //     // valuePropositionIncrease: true,
    //     // decreaseCosts: true,
    //     isQualitative: true,
    //     howToCalculate: "N/A",
    //     KPM: ["contributeCompanyVision", "percentOrTotalChemicalEmissions"],
    // },
    {
        label: "Reduce refrigerant gas emissions",
        htmlLabel: "Reduce refrigerant gas emissions",
        optionValue: "reduceRefrigerantGasEmissions",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "percentOrTotalRefrigerantEmissions"],
    },
    {
        label: "Reduced risk of accident and occupational disease, reduce unsafe acts, improve processes, better instructions, better PM, reduce associated costs",
        htmlLabel: "Reduced risk of accident and occupational disease, reduce unsafe acts, improve processes, better instructions, better PM, reduce associated costs",
        optionValue: "reduceOccupationalDangers",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "productivityRateThroughput", "TRIR", "oshaRecordableIncidents", "oshaNonRecordables", "daysAwayFromWork", "lostTimeInjuryRate", "employeeEngagementSatisfaction", "employeeRetentionRate", "talentTurnoverRate"],
    },
    {
        label: "Reduced noise, exposure & cost of hearing conservation program, Reduced need for protective equipment",
        htmlLabel: "Reduced noise, exposure & cost of hearing conservation program, Reduced need for protective equipment",
        optionValue: "reducedNoiseExposure",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["dollarConsumables", "engineeringSupport", "TRIR", "oshaNonRecordables", "oshaRecordableIncidents", "daysAwayFromWork", "lostTimeInjuryRate", "hearingConservationProgram", "employeeEngagementSatisfaction", "employeeRetentionRate", "talentTurnoverRate"],
    },
    {
        label: "Air quality improvement of ambient air, Reduced need for protective equipment",
        htmlLabel: "Air quality improvement of ambient air, Reduced need for protective equipment",
        optionValue: "improveAmbientAirQuality",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["defectiveProductionDollar", "defectRatePPMorDPM", "totalLbsDust", "numberOfParticles"],
    },
    {
        label: "Improved thermal comfort, reduce unscheduled breaks, heat related illness or absents, reduce security risk due to open doors",
        htmlLabel: "Improved thermal comfort, reduce unscheduled breaks, heat related illness or absents, reduce security risk due to open doors",
        optionValue: "improvedThermalComfort",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["productivityRateThroughput", "energyCostPerUnit", "workspaceOrFactoryFloorComfort", "absenteeism", "employeeEngagementSatisfaction", "employeeRetentionRate", "talentTurnoverRate"],
    },
    {
        label: "Improved visual comfort",
        htmlLabel: "Improved visual comfort",
        optionValue: "improvedVisualComfort",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["productivityRateThroughput", "cycleTimeToMakeGoods", "defectiveProductionDollar", "defectRatePPMorDPM", "qualityCustomerComplaints", "qualityCustomerReturns", "workspaceOrFactoryFloorComfort", "absenteeism", "employeeEngagementSatisfaction", "employeeRetentionRate", "talentTurnoverRate"],
    },
    {
        label: "Improved working environment, job engagement or satisfaction",
        htmlLabel: "Improved working environment, job engagement or satisfaction",
        optionValue: "improvedWorkingEnvironment",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "productivityRateThroughput", "productionCosts", "cycleTimeToMakeGoods", "percentOnTimeToDueDate", "revenuePerEmployee", "perUnitProductCost", "workInProcess", "defectiveProductionDollar", "defectRatePPMorDPM", "qualityCustomerComplaints", "qualityCustomerReturns", "percentProductionYield", "percentShrinkage", "dollarConsumables", "TRIR", "oshaNonRecordables", "oshaRecordableIncidents", "workspaceOrFactoryFloorComfort", "absenteeism", "employeeEngagementSatisfaction", "employeeRetentionRate", "talentTurnoverRate"],
    },
    {
        label: "Change/add quality jobs",
        htmlLabel: "Change/add quality jobs",
        optionValue: "changeAddQualityJobs",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "salesGrowth", "employeeEngagementSatisfaction", "employeeRetentionRate", "talentTurnoverRate"],
    },
    {
        label: "Justice40 Initiatives-decrease burden, exposure; Increase parity, resiliency",
        htmlLabel: "Justice40 Initiatives-decrease burden, exposure; Increase parity, resiliency",
        optionValue: "justice40Initiatives",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "customerSatisfactionRatings", "supplierSatisfactionRatings", "employeeEngagementSatisfaction", "employeeRetentionRate", "talentTurnoverRate"],
    },
    {
        label: "Improved staff satisfaction and loyalty, average years employed",
        htmlLabel: "Improved staff satisfaction and loyalty, average years employed",
        optionValue: "improvedStaffSatisfactionLoyalty",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "productivityRateThroughput", "productionCosts", "cycleTimeToMakeGoods", "percentOnTimeToDueDate", "revenuePerEmployee", "perUnitProductCost", "equipmentDowntime", "percentCapacityUtilization", "overallEquipmentEffectiveness", "forkTruckBreakdownTime", "defectiveProductionDollar", "defectRatePPMorDPM", "qualityCustomerComplaints", "qualityCustomerReturns", "percentProductionYield", "percentShrinkage", "dollarConsumables", "TRIR", "oshaNonRecordables", "oshaRecordableIncidents", "absenteeism", "employeeEngagementSatisfaction", "employeeRetentionRate", "talentTurnoverRate"],
    },
    {
        label: "Reduce staff turnover",
        htmlLabel: "Reduce staff turnover",
        optionValue: "reduceStaffTurnover",
        // riskReduction: true,
        // valuePropositionIncrease: true,
        // decreaseCosts: true,
        isQualitative: true,
        howToCalculate: "N/A",
        KPM: ["contributeCompanyVision", "productivityRateThroughput", "productionCosts", "cycleTimeToMakeGoods", "percentOnTimeToDueDate", "revenuePerEmployee", "perUnitProductCost", "equipmentDowntime", "percentCapacityUtilization", "overallEquipmentEffectiveness", "forkTruckBreakdownTime", "defectiveProductionDollar", "defectRatePPMorDPM", "qualityCustomerComplaints", "qualityCustomerReturns", "percentProductionYield", "percentShrinkage", "dollarConsumables", "TRIR", "oshaNonRecordables", "oshaRecordableIncidents", "absenteeism", "employeeEngagementSatisfaction", "employeeRetentionRate", "talentTurnoverRate"],
    }
]
